'use strict';
const VERSION='0.2.3';
const SITE_URL='https://majestic-profiterole-540cdc.netlify.app';
const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>Array.from(root.querySelectorAll(s));
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const icon=name=>`<svg aria-hidden="true"><use href="#${name}"/></svg>`;
const instruments=[{"name":"琵琶","english":"PIPA","image":"pipa","line":"“转轴拨弦三两声，未成曲调先有情。”","role":"“转轴拨弦三两声，未成曲调先有情。”","details":[["形制与古韵","乐器形制可追溯至唐宋，至今仍保持着古老的横抱弹奏姿势"],["乐声与角色","琵琶也分南北，北琵铿锵，南琶温润。它是南音的灵魂，是曲子的骨干音。拨弦奏出曲子的骨干音。南音谱中还记着琵琶指法，把旋律与弹奏联系起来"]]},{"name":"洞箫","english":"DONGXIAO","image":"xiao","line":"“箫音阵阵引凤来。”","role":"“箫音阵阵引凤来。”","details":[["形制与古韵","竹制，延续唐代“尺八”的六孔规制，选竹讲究“十目九节”。是南音中保留古乐遗韵的重要乐器"],["乐声与角色","它吹奏主旋律，与弦乐相和，一口气之间，让声音缓缓展开"]]},{"name":"二弦","english":"ERXIAN","image":"erxian","line":"“箫咬弦，弦入箫。”","role":"“箫咬弦，弦入箫。”","details":[["形制与古韵","上四管中唯一的弓弦乐器，音色温润，最接近人声。模样保留着古老弓弦乐器的形制"],["乐声与角色","持续的弓声与洞箫相伴，把旋律中的线条拉得细而长"]]},{"name":"三弦","english":"SANXIAN","image":"sanxian","line":"“三弦轻响，韵潜心底。”","role":"“三弦轻响，韵潜心底。”","details":[["形制与古韵","琴杆无品，音色低沉。从古老的弹拨乐器演变而来，"],["乐声与角色","与琵琶相应，补充旋律骨干与余韵。它是拨弦乐器；合奏中的拍节另有拍板"]]}];
const eras=[{"node":"老馆阁","date":"上世纪","label":"老馆阁 · 上世纪","image":"old-hall","alt":"老馆阁弦友围坐的场景创作插画，非历史照片","quote":"一支曲子悠悠唱上一整夜","story":"上世纪的南音馆阁里，老辈人围坐「拼馆」、搭锦棚，一支曲子悠悠唱上一整夜"},{"node":"苏统谋","date":"1939—2022","label":"苏统谋 · 留住了谱","image":"su-tongmou","alt":"苏统谋照片（小组提供）","quote":"留住了南音的「谱」","story":"苏统谋（1939—2022）：国家级非遗代表性传承人。把一本本老曲谱整理出版，留住了南音的「谱」","extension":"jpg","portrait":true},{"node":"李白燕","date":"1966—","label":"李白燕 · 留下唱法","image":"li-baiyan","alt":"李白燕照片（小组提供）","quote":"把唱法一字一句留了下来","story":"李白燕（1966—）：国家级非遗代表性传承人、国家一级演员。编著南音演唱教程，把唱法一字一句留了下来","extension":"jpg","portrait":true},{"node":"庄丽芬","date":"「80 后」","label":"庄丽芬 · 把南音带向远方","image":"zhuang-lifen","alt":"庄丽芬照片（小组提供）","quote":"进校园、上央视、走到海外","story":"庄丽芬（「80 后」）：泉州市南音传承中心负责人，曾于2018年成为福建省当时最年轻的「牡丹奖」得主。带着南音进校园、上央视、走到海外","extension":"png","portrait":true},{"node":"年轻新声","date":"今天","label":"今天 · 年轻的新声","image":"young-musicians","alt":"年轻人在天井学习南音的场景创作插画","quote":"年轻的人正把它唱成新的样子","story":"今天，南音从幼儿园唱到大学，社团遍布泉州街巷<br>年轻人把它混进电音、说唱和流行歌，让它悄悄破圈"}];
const notes=[{"glyph":"乂","degree":"1","name":"宫","hint":"是整首曲子的根。","freq":261.63},{"glyph":"工","degree":"2","name":"商","hint":"清亮的骨干音","freq":293.66},{"glyph":"六","degree":"3","name":"角","hint":"常走在旋律的眉眼处","freq":329.63},{"glyph":"思","degree":"5","name":"徵","hint":"南音里最稳的那一笔","freq":392},{"glyph":"一","degree":"6","name":"羽","hint":"收尾常落在这里","freq":440}];
const endings={"listen":["它从某个院墙里飘出来，不急不慢，像有人在你耳边轻轻说话","你也许听不懂歌词，但那口气、那声调，忽然就让人安心下来","它来过一次，就会在你心里留一个位置"],"learn":["千年的谱就在那里，等你开口","从「乂」开始，慢慢来","不用急着唱得多好，愿意学习的每一步都在传承"],"share":["声音也许会停，但故事不会","南音能活一千年，靠的就是一个接一个，讲给下一个人","——下一声，就靠你了"]};

// Decorative layers contain no reading content. Copy remains selectable HTML.
$$('.chapter').forEach(section=>{section.insertAdjacentHTML('afterbegin','<div class="paper-grain" aria-hidden="true"></div><div class="ink-field" aria-hidden="true"><i></i><i></i><i></i><i></i></div><svg class="ornament" aria-hidden="true"><use href="#flower"/></svg>');});
$$('.origin-sheet').forEach(sheet=>sheet.insertAdjacentHTML('afterbegin','<svg class="ornament" aria-hidden="true"><use href="#flower"/></svg>'));
$('#instrument-track').innerHTML=instruments.map((data,i)=>`<article class="instrument-card paper-card" data-instrument="${i}"><figure><img src="assets/${data.image}.webp" width="1122" height="1380" alt="${data.name}创作插画" loading="lazy" draggable="false"></figure><button class="instrument-info" type="button" data-instrument="${i}" aria-haspopup="dialog"><span class="instrument-index">上四管 <b>0${i+1}</b></span><h3>${data.name}</h3><span class="english-name">${data.english}</span><p>${data.line}</p><span class="expand-label">展开介绍 <span aria-hidden="true">⌄</span></span></button></article>`).join('');
$('.timeline').innerHTML=eras.map((era,i)=>`<button type="button" role="tab" id="era-tab-${i}" data-era="${i}" aria-selected="${i===0}" aria-controls="era-panel" tabindex="${i===0?0:-1}"><span class="era-dot"></span><span>${era.node}<small>${era.date}</small></span></button>`).join('');
const scoreColumns=[[0,1,2,3],[4,3,2,1],[0,2,1,4],[3,4,0,2]];
$('#score-grid').innerHTML=scoreColumns.map(column=>`<div class="score-column">${column.map(n=>`<button type="button" class="score-character" data-note="${n}" aria-label="谱字${notes[n].glyph}，${notes[n].name}，入门示意${notes[n].degree}">${notes[n].glyph}</button>`).join('')}</div>`).join('');
function addCorners(root=document){$$('.paper-card',root).forEach(card=>{if($('.card-corner',card))return;card.insertAdjacentHTML('beforeend',Array.from({length:4},()=>'<svg class="card-corner" aria-hidden="true"><use href="#corner"/></svg>').join(''));});}
addCorners();
const title=$('.glyph-title');const titleText=title.textContent;title.setAttribute('aria-label',titleText);title.innerHTML=Array.from(titleText).map((letter,i)=>`<span aria-hidden="true" style="--i:${i}">${letter}</span>`).join('');
if('IntersectionObserver' in window){document.body.classList.add('js-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.14});$$('.reveal').forEach(element=>observer.observe(element));}

let toastTimer;function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function ripple(event){if(reducedMotion.matches)return;const dot=document.createElement('span');dot.className='ink-ripple';dot.setAttribute('aria-hidden','true');const box=event.currentTarget?.getBoundingClientRect?.();dot.style.left=`${event.clientX||box?.left+box?.width/2||innerWidth/2}px`;dot.style.top=`${event.clientY||box?.top+box?.height/2||innerHeight/2}px`;document.body.append(dot);setTimeout(()=>dot.remove(),1300);}
let activeDialog=null;let lastFocus=null;
function openDialog(dialog){if(activeDialog){activeDialog.close();}lastFocus=document.activeElement;activeDialog=dialog;document.body.classList.add('dialog-open');dialog.showModal();}
function closeDialog(dialog){dialog.close();}
$$('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{if(activeDialog===dialog){activeDialog=null;document.body.classList.remove('dialog-open');lastFocus?.focus({preventScroll:true});}});dialog.addEventListener('click',event=>{const rect=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom))closeDialog(dialog);});$('.dialog-close',dialog).addEventListener('click',()=>closeDialog(dialog));});
document.addEventListener('click',event=>{const button=event.target.closest('[data-open]');if(button){openDialog(document.getElementById(button.dataset.open));ripple(event);}const anchor=event.target.closest('a[href^="#"]');if(!anchor)return;const target=document.querySelector(anchor.getAttribute('href'));if(!target)return;event.preventDefault();if(activeDialog)closeDialog(activeDialog);target.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'start'});history.replaceState(null,'',anchor.getAttribute('href'));const overlay=$('#ink-transition');overlay.classList.remove('flowing');void overlay.offsetWidth;overlay.classList.add('flowing');});
const chapters=$$('.chapter');let currentChapter=0;let scrollFrame;
function updateChapter(){const sample=innerHeight*.4;let index=0;chapters.forEach((chapter,i)=>{if(chapter.getBoundingClientRect().top<=sample)index=i;});const night=index===0||index===5;document.body.classList.toggle('is-night',night);$$('.chapter-nav a').forEach((anchor,i)=>{if(i===index)anchor.setAttribute('aria-current','step');else anchor.removeAttribute('aria-current');});if(index!==currentChapter){if(audio.playing)audio.stop();currentChapter=index;}scrollFrame=null;}
window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateChapter);},{passive:true});window.addEventListener('resize',updateChapter);

// Audio is synthesized locally, initiated exclusively by an explicit user gesture.
// It is an illustration of timbre/density, never presented as a Nanyin recording.
class SoundEngine{
 constructor(){this.context=null;this.master=null;this.nodes=new Set();this.playing=false;this.mode=null;this.muted=false;this.timer=null;this.run=0;}
 async init(){if(!this.context){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error('当前浏览器不支持声音体验，可继续阅读。');this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=.45;const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-22;limiter.ratio.value=8;this.master.connect(limiter);limiter.connect(this.context.destination);}if(this.context.state!=='running')await this.context.resume();}
 register(node){this.nodes.add(node);node.onended=()=>{this.nodes.delete(node);try{node.disconnect();}catch{}};return node;}
 voice(type,freq,start,length,volume=.1){const c=this.context;const envelope=c.createGain();const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=type==='pluck'?2200:1100;filter.Q.value=.3;filter.connect(envelope);envelope.connect(this.master);const attack=type==='pluck'?.012:.3;envelope.gain.setValueAtTime(.0001,start);envelope.gain.linearRampToValueAtTime(volume,start+Math.min(attack,length/4));envelope.gain.exponentialRampToValueAtTime(.0001,start+length);
  if(type==='pluck'){const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*length),c.sampleRate);const samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++){const t=i/c.sampleRate;let value=0;for(let h=1;h<=6;h++)value+=Math.sin(2*Math.PI*freq*h*t)*Math.exp(-t*(1.3+h*.75))/h;samples[i]=value*.6;}const node=this.register(c.createBufferSource());node.buffer=buffer;node.connect(filter);node.start(start);node.stop(start+length+.03);
  }else{const osc=this.register(c.createOscillator());osc.type=type==='bow'?'triangle':'sine';osc.frequency.setValueAtTime(freq,start);if(type!=='vowel'){const vibrato=c.createOscillator();const depth=c.createGain();vibrato.frequency.value=4.4;depth.gain.value=freq*.002;vibrato.connect(depth);depth.connect(osc.frequency);this.register(vibrato);vibrato.start(start);vibrato.stop(start+length);}
   if(type==='vowel'){filter.type='bandpass';filter.frequency.value=650;filter.Q.value=.8;}osc.connect(filter);osc.start(start);osc.stop(start+length+.03);
   if(type==='flute'){const overtone=this.register(c.createOscillator());const quiet=c.createGain();quiet.gain.value=.07;overtone.frequency.value=freq*2;overtone.connect(quiet);quiet.connect(filter);overtone.start(start);overtone.stop(start+length);}}
  setTimeout(()=>{try{envelope.disconnect();filter.disconnect();}catch{}},Math.max(0,(start+length-c.currentTime)*1000+500));
 }
 beat(start){const c=this.context;const n=c.createBuffer(1,c.sampleRate*.09,c.sampleRate);const data=n.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*12);const source=this.register(c.createBufferSource());source.buffer=n;const band=c.createBiquadFilter();band.type='bandpass';band.frequency.value=900;band.Q.value=1.3;const gain=c.createGain();gain.gain.value=.035;source.connect(band);band.connect(gain);gain.connect(this.master);source.start(start);source.stop(start+.09);setTimeout(()=>{band.disconnect();gain.disconnect();},Math.max(0,(start-c.currentTime)*1000+400));}
 async start(mode,era=0){const run=++this.run;try{await this.init();if(run!==this.run)return;this.clearNodes();this.muted=false;this.master.gain.setTargetAtTime(.45,this.context.currentTime,.08);this.playing=true;this.mode=mode;const sequence=[0,2,1,3,4,2,1,0];const spacing=mode==='cover'?2.6:era===4?1.45:2.1;const base=this.context.currentTime+.08;sequence.forEach((n,i)=>{const start=base+i*spacing;const freq=notes[n].freq*(era===4?1.25:1);this.voice('flute',freq,start,spacing*1.7,.1);if(mode==='cover'&&i%3===1)this.voice('pluck',freq/2,start+.45,2,.055);if(mode==='era'&&era>=1){this.voice('pluck',freq/2,start+.16,1.8,.07);if(i%2===0)this.beat(start);}if(mode==='era'&&era>=2){this.voice('bow',freq,start+.24,spacing*1.4,.027);this.voice('pluck',freq/2,start+.4,1.4,.035);}if(mode==='era'&&era===3)this.voice('vowel',freq/2,start+.3,spacing*1.3,.03);});this.timer=setTimeout(()=>this.stop(),(sequence.length*spacing+spacing)*1000);updateAudioUI();if(mode==='cover'){clearTimeout(coverReadyTimer);coverReadyTimer=setTimeout(showCoverNext,3000);}
  }catch(error){toast(error.message||'声音暂时无法播放，可继续阅读。');this.playing=false;updateAudioUI();}}
 clearNodes(){clearTimeout(this.timer);this.nodes.forEach(node=>{try{node.stop();node.disconnect();}catch{}});this.nodes.clear();}
 stop(){this.run++;this.clearNodes();this.playing=false;this.mode=null;updateAudioUI();}
 async touchNote(freq){if(!this.context||this.muted)return;try{await this.init();this.voice('pluck',freq,this.context.currentTime+.02,1.8,.065);}catch{}}
 async smallEffect(stamp=false){if(!this.context||this.muted)return;try{await this.init();if(stamp)this.beat(this.context.currentTime+.02);else this.voice('pluck',notes[0].freq/2,this.context.currentTime+.02,2,.07);}catch{}}
}
const audio=new SoundEngine();let coverReadyTimer;
function showCoverNext(){$('#cover-next').classList.add('ready');}
function updateAudioUI(){const on=audio.playing&&!audio.muted;document.body.classList.toggle('sound-on',on);$('#sound-toggle').setAttribute('aria-pressed',String(on));$('#sound-toggle').setAttribute('aria-label',on?'静音声音':audio.context?'开启声音':'开启声音示意');$('#sound-label').textContent=on?'有声':'静音';const cover=on&&audio.mode==='cover';$('#cover-play').setAttribute('aria-pressed',String(cover));$('#cover-play').setAttribute('aria-label',cover?'停止声音示意':'播放声音示意');$('#cover-play svg use').setAttribute('href',cover?'#pause-icon':'#play-icon');$('#chapter-1').classList.toggle('is-playing',cover);$('#cover-prompt').textContent=cover?'让这一声，慢慢展开':'点击灯下的圆点，听一声';const era=on&&audio.mode==='era';$('#era-play').setAttribute('aria-pressed',String(era));$('#era-play').setAttribute('aria-label',era?'停止声音示意':'播放当前章节的声音示意');$('#era-play svg use').setAttribute('href',era?'#pause-icon':'#play-icon');}
$('#cover-play').addEventListener('click',event=>{ripple(event);if(audio.playing&&audio.mode==='cover')audio.stop();else audio.start('cover');});
$('#sound-toggle').addEventListener('click',()=>{if(!audio.context){audio.start(currentChapter===4?'era':'cover',selectedEra);return;}audio.muted=!audio.muted;audio.master.gain.setTargetAtTime(audio.muted?0:.45,audio.context.currentTime,.08);if(!audio.muted&&!audio.playing)audio.start(currentChapter===4?'era':'cover',selectedEra);updateAudioUI();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.stop();if(audio.context?.state==='running')audio.context.suspend();}else checkVersion();});

const track=$('#instrument-track');let cardIndex=0;
function nearestCard(){let distance=Infinity,index=0;const left=track.getBoundingClientRect().left+parseFloat(getComputedStyle(track).paddingLeft);$$('.instrument-card').forEach((card,i)=>{const delta=Math.abs(card.getBoundingClientRect().left-left);if(delta<distance){distance=delta;index=i;}});return index;}
function updateCarousel(){cardIndex=nearestCard();$('#instrument-count').textContent=`0${cardIndex+1} / 04`;$('#instrument-progress').style.transform=`translateX(${cardIndex*100}%)`;$('#instrument-prev').disabled=cardIndex===0;$('#instrument-next').disabled=cardIndex===3;}
function goCard(index){index=Math.max(0,Math.min(3,index));const card=$$('.instrument-card')[index];track.scrollTo({left:card.offsetLeft-parseFloat(getComputedStyle(track).paddingLeft),behavior:reducedMotion.matches?'instant':'smooth'});}
track.addEventListener('scroll',updateCarousel,{passive:true});$('#instrument-prev').addEventListener('click',()=>goCard(cardIndex-1));$('#instrument-next').addEventListener('click',()=>goCard(cardIndex+1));track.addEventListener('keydown',event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();goCard(cardIndex+(event.key==='ArrowRight'?1:-1));}});
let drag=null;let suppressClick=false;
track.addEventListener('pointerdown',event=>{if(event.pointerType!=='mouse'||event.button!==0)return;drag={x:event.clientX,scroll:track.scrollLeft,moved:false,card:event.target.closest('.instrument-card')};});
window.addEventListener('pointermove',event=>{if(!drag)return;const delta=event.clientX-drag.x;if(Math.abs(delta)>6){drag.moved=true;track.style.scrollSnapType='none';track.scrollLeft=drag.scroll-delta;if(drag.card&&!reducedMotion.matches)drag.card.style.transform=`perspective(1000px) rotateY(${Math.max(-6,Math.min(6,delta/16))}deg)`;event.preventDefault();}},{passive:false});
function endDrag(){if(!drag)return;const moved=drag.moved;if(drag.card)drag.card.style.transform='';drag=null;track.style.scrollSnapType='';if(moved){suppressClick=true;goCard(nearestCard());setTimeout(()=>suppressClick=false,100);}}
window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);
track.addEventListener('click',event=>{const button=event.target.closest('button[data-instrument]');if(!button||suppressClick)return;const data=instruments[Number(button.dataset.instrument)];$('#instrument-detail').innerHTML=`<span class="english-name">上四管 · ${data.english}</span><h2 id="instrument-dialog-title">${data.name}</h2><p class="detail-role">${data.role}</p>${data.details.map(([heading,text])=>`<section class="detail-section"><h3>${heading}</h3><p>${text}</p></section>`).join('')}<p class="small-note">插画为创作示意；形制说明见资料来源。</p>`;ripple(event);openDialog($('#instrument-dialog'));});
$('#score-grid').addEventListener('click',event=>{const button=event.target.closest('[data-note]');if(!button)return;const data=notes[Number(button.dataset.note)];$$('.score-character').forEach(node=>node.classList.toggle('active',node===button));const slip=$('#note-slip');slip.classList.remove('is-shown');slip.innerHTML=`<div class="note-meta"><strong class="note-glyph">${data.glyph}</strong><dl><div><dt>谱字</dt><dd>${data.glyph}</dd></div><div><dt>简谱</dt><dd>${data.degree} · 入门示意</dd></div><div><dt>五音</dt><dd>${data.name}</dd></div></dl></div><p class="note-description">${data.hint}</p><div class="seal" aria-label="南音">南音</div>`;addCorners();void slip.offsetWidth;slip.classList.add('is-shown');ripple(event);audio.touchNote(data.freq);requestAnimationFrame(()=>{const bottom=slip.getBoundingClientRect().bottom;const limit=innerHeight-100;if(bottom>limit)window.scrollBy({top:bottom-limit+20,behavior:reducedMotion.matches?'instant':'smooth'});});});
let selectedEra=0;let sceneRun=0;let sceneTimer;
function selectEra(index,play=false){selectedEra=index;const era=eras[index];const run=++sceneRun;clearTimeout(sceneTimer);$$('[data-era]').forEach((node,i)=>{node.setAttribute('aria-selected',String(i===index));node.tabIndex=i===index?0:-1;});$('#era-panel').setAttribute('aria-labelledby',`era-tab-${index}`);$('#era-label').textContent=era.label;$('#era-quote').innerHTML=era.quote;$('#era-story').innerHTML=`<p>${era.story}</p>${era.more?`<details><summary>再读一点 <span aria-hidden="true">＋</span></summary><p>${era.more}</p></details>`:''}`;addCorners();const a=$('#era-image-a'),b=$('#era-image-b');b.style.opacity='0';const image=new Image();image.onload=()=>{if(run!==sceneRun)return;$('#era-panel').classList.toggle('is-portrait',Boolean(era.portrait));b.src=image.src;b.alt=era.alt;b.style.transform=era.portrait?'scale(1)':'scale(1.04)';requestAnimationFrame(()=>{if(run!==sceneRun)return;b.style.opacity='1';b.style.transform='scale(1)';});sceneTimer=setTimeout(()=>{if(run!==sceneRun)return;a.src=image.src;a.alt=era.alt;b.style.opacity='0';},reducedMotion.matches?0:850);};image.src=`assets/${era.image}.${era.extension||'webp'}`;if(play)audio.start('era',index);else if(audio.playing)audio.stop();}
$('.timeline').addEventListener('click',event=>{const button=event.target.closest('[data-era]');if(!button)return;const continuePlaying=audio.playing&&audio.mode==='era';selectEra(Number(button.dataset.era),continuePlaying);ripple(event);});
$('.timeline').addEventListener('keydown',event=>{const keys={ArrowDown:1,ArrowUp:-1,ArrowRight:1,ArrowLeft:-1};let next=selectedEra;if(event.key in keys)next=(next+keys[event.key]+5)%5;else if(event.key==='Home')next=0;else if(event.key==='End')next=4;else return;event.preventDefault();selectEra(next,audio.playing&&audio.mode==='era');$(`#era-tab-${next}`).focus();});
$('#era-play').addEventListener('click',event=>{ripple(event);if(audio.playing&&audio.mode==='era')audio.stop();else audio.start('era',selectedEra);});
let endingTimers=[];let endingRun=0;
function resetEnding(){endingRun++;endingTimers.forEach(clearTimeout);endingTimers=[];$('#chapter-6').classList.remove('is-selected');$('#chapter-6').style.minHeight='';$('#ending-intro').inert=false;$('#ending-result').hidden=true;$('#ending-seal').hidden=true;$('#ending-lines').innerHTML='';$$('[data-ending]').forEach(button=>{button.classList.remove('selected','dimmed');button.disabled=false;});}
function chooseEnding(choice,event){resetEnding();const run=++endingRun;$$('[data-ending]').forEach(button=>{button.classList.add(button.dataset.ending===choice?'selected':'dimmed');button.disabled=true;});audio.smallEffect();ripple(event);const intro=$('#ending-intro');intro.inert=true;$('#chapter-6').classList.add('is-selected');const lines=endings[choice];$('#ending-lines').innerHTML=lines.map(line=>`<p>${line}</p>`).join('');$('#ending-result').hidden=false;requestAnimationFrame(()=>{const result=$('#ending-result');$('#chapter-6').style.minHeight=`${result.offsetTop+result.offsetHeight+170}px`;result.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'start'});});$('#ending-result').focus({preventScroll:true});const gap=reducedMotion.matches?100:600;$$('#ending-lines p').forEach((line,i)=>endingTimers.push(setTimeout(()=>{if(run===endingRun)line.classList.add('visible');},(reducedMotion.matches?0:500)+i*gap)));endingTimers.push(setTimeout(()=>{if(run!==endingRun)return;$('#ending-seal').hidden=false;audio.smallEffect(true);},(reducedMotion.matches?400:1700)+(lines.length-1)*gap));}
$$('[data-ending]').forEach(button=>button.addEventListener('click',event=>chooseEnding(button.dataset.ending,event)));$('#choose-again').addEventListener('click',()=>{resetEnding();$('[data-ending]').focus({preventScroll:true});});$('#replay').addEventListener('click',()=>{resetEnding();audio.stop();});
$('#share-button').addEventListener('click',async()=>{const shareData={title:'泉州南音 · 一声千年',text:'这一声，交给你。',url:SITE_URL};try{if(navigator.share){await navigator.share(shareData);return;}if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(SITE_URL);toast('链接已复制，把这一声讲给下一个人。');return;}window.prompt('复制这个链接，讲给下一个人：',SITE_URL);}catch(error){if(error.name!=='AbortError')toast('请从浏览器菜单分享，或复制网页地址。');}});
let checkingVersion=false;async function checkVersion(){if(checkingVersion||document.hidden)return;checkingVersion=true;try{const response=await fetch(`version.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const data=await response.json();if(data.version&&data.version!==VERSION)$('#update-banner').hidden=false;}catch{}finally{checkingVersion=false;}}
$('#refresh-version').addEventListener('click',()=>location.reload());$('#dismiss-update').addEventListener('click',()=>$('#update-banner').hidden=true);window.addEventListener('pageshow',()=>{updateChapter();checkVersion();});setInterval(checkVersion,60000);updateCarousel();updateChapter();
